BASE=../..

include $(BASE)/rule/def.mk

APP_TARGET=am_av_test am_av_server

am_av_test_SRCS=am_av_test.c
am_av_test_LIBS=../../am_adp/am_adp

am_av_server_SRCS=am_av_server.c

include $(BASE)/rule/rule.mk
