BASE=../../../..

include $(BASE)/rule/def.mk

CFLAGS+=-I$(ROOTDIR)/include/am_mw/libdvbsi -I$(ROOTDIR)/include/am_mw/libdvbsi/tables
O_TARGET=tables
tables_SRCS=cat.c     eit.c     nit.c     pat.c     pmt.c     sdt.c     tot.c	bat.c

include $(BASE)/rule/rule.mk
