#!/bin/sh

APP=am_dvr_test
BASE=../..
RELPATH=test/am_dvr_test

DIRNAME=`dirname $0`
ROOT=${DIRNAME}/${BASE}

if [ "x$TARGET" = "x" ]; then
	TARGET=`grep TARGET ${ROOT}/config/config.mk | sed s+TARGET=++`
fi

${ROOT}/build/${TARGET}/${RELPATH}/${APP} $@
