BASE=../..

include $(BASE)/rule/def.mk

APP_TARGET=am_dsc_test am_dsc_test2
am_dsc_test_SRCS=am_dsc_test.c
am_dsc_test_LIBS=../../am_adp/am_adp

am_dsc_test2_SRCS=am_dsc_test2.c
am_dsc_test2_LIBS=../../am_adp/am_adp

include $(BASE)/rule/rule.mk
